### ISSUE TITLE
Posts Page 제작

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#16]
## Task
청원 글 목록 제작

페이지네이션은 고려하지 않습니다.

## Task List
- [x] 게시글 목록 UI 제작
- [x] 버튼, 필터 UI 제작
- [x] GET Posts API 연동
- [x] 페이지네이션과 게시판 연결

API 연동 관련 새로운 이슈가 작성됐으니 본 이슈는 닫습니다.

**Comment by gpgun0** [comment]
API 연동 관련 새로운 이슈가 작성됐으니 본 이슈는 닫습니다.
