### ISSUE TITLE
Post Page 제작

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#17]
## Task
청원 게시글 열람 페이지 제작

## Task List
- [x] 청원 게시글 페이지 제작
- [x] 댓글 창 UI 제작
- [x] 동의하기 UI 제작
- [ ] 게시글 API 연동
- [ ] 댓글 API 연동
- [ ] 동의하기 API 연동
